### ISSUE TITLE
Request for pygreat pip3 package update

### ISSUE THREAD

**Issue by decidedlygray** [greatscottgadgets/libgreat#18]
Hello there,

I'm not quite sure where to put this ticket. I know you all have done a fantastic job of keeping the firmware of the GreatFET One and the software in sync, packaged together (currently 2019.9.1).

Currently the pygreat-2019.9.1 package is missing a somewhat "critical" fix: https://github.com/greatscottgadgets/libgreat/commit/655a6a680ab1c52d4319d8825e657c04d9f1067e (addresses https://github.com/greatscottgadgets/libgreat/issues/7)

Without that update, anyone using Python 3.5+ won't be able to use the library. `comms.py` crashes right away during device setup.

I was wondering: can you package up a 2019.12.1 version of pygreat into pypi?

Tested on Ubuntu 18.04.3 LTS, Python 3.6.9 (currently the default install for Ubuntu 18)

Thank you for your time, and keep up the great work!

### Temporary Workaround for Ubuntu 18 Users
As a dirty workaround to anyone using Ubuntu 18 that happens upon this issue, you can manually work around by changing this line in `comms.py` (check your stack trace for the dist-packages location of pygreat):
```
            if match.groups(1) is None:
                return 1
            else:
                return int(match.groups(1))
```
To:
```
            if match.groups(1) is None:
                return 1
            else:
                return int(match.groups(1)[0])
```

**Comment by decidedlygray** [comment]
Also affects the latest Raspbian (runs Python3.7)

**Comment by ktemkin** [comment]
A release will come relatively soon; once I'm recovered from a long stint of travel. :)

In the interim, feel free to grab the latest nightlies:

https://nightlies.ktemkin.com/greatfet/2019/12/

You can install these with pip by providing the URL directly; e.g.:

```
pip3 install --user https://nightlies.ktemkin.com/greatfet/2019/12/pygreat-2019_12_03_build_554_git_598024e_auto_nightly-py2.py3-none-any.whl
pip3 install --user https://nightlies.ktemkin.com/greatfet/2019/12/GreatFET-2019_12_03_build_554_git_598024e_auto_nightly-py2.py3-none-any.whl

**Comment by Qyriad** [comment]
This was done last week: https://github.com/greatscottgadgets/greatfet/releases/tag/v2021.2.1
